services:
    $ACCOUNT_SERVER_CONTAINER_NAME:
        container_name: $ACCOUNT_SERVER_CONTAINER_NAME
        image: $ACCOUNT_SERVER_CONTAINER_NAME:$BUILD_NUMBER
        init: true
        restart: unless-stopped
        volumes:
            - $SERVER_VOLUME_NAME:/server/files
        networks:
            - $NETWORK_NAME

volumes:
    $SERVER_VOLUME_NAME:
        name: $SERVER_VOLUME_NAME

networks:
    $NETWORK_NAME:
        name: $NETWORK_NAME
        external: true
