services:
    $REDIS_CONTAINER_NAME:
        container_name: $REDIS_CONTAINER_NAME
        image: redis:7.2.4-alpine3.19
        init: true
        restart: unless-stopped
        volumes:
            - $REDIS_VOLUME_NAME:/data
        networks:
            - $NETWORK_NAME
        command: redis-server --requirepass $REDIS_PASSWORD

volumes:
    $REDIS_VOLUME_NAME:
        name: $REDIS_VOLUME_NAME

networks:
    $NETWORK_NAME:
        name: $NETWORK_NAME
        external: true
