services:
    $DATABASE_CONTAINER_NAME:
        container_name: $DATABASE_CONTAINER_NAME
        image: postgres:16.2-alpine3.19
        init: true
        restart: unless-stopped
        environment:
            POSTGRES_USER: $DATABASE_CREDENTIALS_USR
            POSTGRES_PASSWORD: $DATABASE_CREDENTIALS_PSW
            POSTGRES_DB: $DATABASE_NAME
        volumes:
            - $DATABASE_VOLUME_NAME:/var/lib/postgresql/data
        networks:
            - $NETWORK_NAME

volumes:
    $DATABASE_VOLUME_NAME:
        name: $DATABASE_VOLUME_NAME

networks:
    $NETWORK_NAME:
        name: $NETWORK_NAME
        external: true
